### Test

GET http://localhost:3003/ping


### Criar Usuário

POST http://localhost:3003/signup/new-user
Content-Type: application/json

{
    "name": "Ricardo",
	"email": "exemplo@lbn.com",
	"password": "123456"
}
