### Test

GET http://localhost:3003/ping


### Criar Usuário

POST http://localhost:3003/signup/new-user
Content-Type: application/json

{
    "name": "Sandra2",
	"email": "exemplo-sand@lbn.com",
	"password": "6544"
}

###

GET http://localhost:3003/teste
