### Test

GET http://localhost:3003/ping


### Criar Usuário

POST http://localhost:3003/signup/new-user
Content-Type: application/json

{
    "name": "Roger",
	"email": "exemplo-roger@lbn.com",
	"password": "654321"
}

###

GET http://localhost:3003/teste
